package hieu.constant;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class GlobalPath {

    public static final String[] EXCLUDE_LIST = new String[]{
            "https://techbox.vn/gia-treo-tivi.html",
            "https://boba.vn/me-va-be",
            "https://techbox.vn/gia-dung-thong-minh.html",
            "https://boba.vn/o-to-xe-may",
            "https://boba.vn/do-choi-tre-em",
            "https://boba.vn/may-anh-may-bay-flycam",
            "https://boba.vn/android-tivi-box"
    };

    public static final String PERSISTENCE_UNIT = "SuggestionPU";

    public static final String TECHBOX_URL = "https://techbox.vn";
    public static final String TECHBOX_CATEGORY_XSL = "/WEB-INF/techbox/category.xsl";
    public static final String TECHBOX_CATEGORY_XSD = "/WEB-INF/techbox/category.xsd";
    public static final String TECHBOX_MAX_PAGE_XSL = "/WEB-INF/techbox/maxPage.xsl";
    public static final String TECHBOX_PRODUCT_URL_XSL = "/WEB-INF/techbox/productUrl.xsl";
    public static final String TECHBOX_PRODUCT_DETAIL_XSL = "/WEB-INF/techbox/product.xsl";
    public static final String TECHBOX_PRODUCT_DETAIL_XSD = "/WEB-INF/techbox/product.xsd";
    public static final String TECHBOX_PRODUCT_IMAGE_URL_XSL = "/WEB-INF/techbox/productImageUrl.xsl";
    public static final String TECHBOX_PRODUCT_BACKUP_IMAGE_URL_XSL = "/WEB-INF/techbox/productSubImageUrl.xsl";
    public static final String TECHBOX_PRODUCT_DESCRIPTION_XSL = "/WEB-INF/techbox/productDescription.xsl";

    public static final String BOBA_URL = "https://boba.vn";
    public static final String BOBA_CATEGORY_XSL = "/WEB-INF/boba/category.xsl";
    public static final String BOBA_CATEGORY_XSD = "/WEB-INF/boba/category.xsd";
    public static final String BOBA_MAX_PAGE_XSL = "/WEB-INF/boba/maxPage.xsl";
    public static final String BOBA_PRODUCT_URL_XSL = "/WEB-INF/boba/productUrl.xsl";
    public static final String BOBA_PRODUCT_DETAIL_XSL = "/WEB-INF/boba/product.xsl";
    public static final String BOBA_PRODUCT_DETAIL_XSD = "/WEB-INF/boba/product.xsd";
    public static final String BOBA_PRODUCT_DESCRIPTION_XSL = "/WEB-INF/boba/productDescription.xsl";

    public static final String REPORT_PDF_XSL = "/WEB-INF/pdf/report-pdf.xsl";
    public static final String PDF_CONFIG = "/WEB-INF/fop.xconf";

    public static final Map<String, String[]> MAPPING_USAGE;

    static {
        Map<String, String[]> mapping = new HashMap<>();
        mapping.put("https://techbox.vn/phu-kien.html", new String[]{"working", "living"});
        mapping.put("https://techbox.vn/dau-phat-hd.html", new String[]{"working", "living"});
        mapping.put("https://techbox.vn/camera-ip.html", new String[]{"working", "living", "kitchen", "hallway", "bed", "yard", "garage", "other"});
        mapping.put("https://techbox.vn/loa-bluetooth.html", new String[]{"working", "living"});
        mapping.put("https://techbox.vn/android-tv-box.html", new String[]{"working", "living"});

        mapping.put("https://boba.vn/loa-bluetooth", new String[]{"working", "living"});
        mapping.put("https://boba.vn/loa-keo-di-dong-gia-re", new String[]{"working", "living"});
        mapping.put("https://boba.vn/loa-xach-tay-di-dong-karaoke", new String[]{"working", "living"});
        mapping.put("https://boba.vn/loa-may-tinh", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/tai-nghe-bluetooth", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/tai-nghe-kiem-am", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/tai-nghe-true-wireless", new String[]{"working", "living", "hallway", "bed"});
        mapping.put("https://boba.vn/tai-nghe-bluetooth-mot-ben", new String[]{"working", "other"});
        mapping.put("https://boba.vn/may-ghi-am", new String[]{"working", "other"});
        mapping.put("https://boba.vn/may-nghe-nhac-mp3-lossless", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/may-ghi-am-chuyen-nghiep", new String[]{"working"});
        mapping.put("https://boba.vn/chan-gia-kep-micro-thu-am", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/phu-kien-micro-thu-am-chuyen", new String[]{"working"});
        mapping.put("https://boba.vn/soundcard-thu-am-chuyen-nghiep", new String[]{"working"});
        mapping.put("https://boba.vn/hop-chup-san-pham-co-den", new String[]{"working"});
        mapping.put("https://boba.vn/mic-thu-am-livestream", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/micro-bluetooth", new String[]{"working", "living", "hallway"});
        mapping.put("https://boba.vn/micro-thu-am-chuyen-nghiep", new String[]{"working"});
        mapping.put("https://boba.vn/micro-co-day-karaoke", new String[]{"working", "living", "hallway"});
        mapping.put("https://boba.vn/micro-khong-day", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/micro-cho-dien-thoai", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/micro-thu-am-may-tinh", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/micro-livestream-cong-usb", new String[]{"working", "hallway"});
        mapping.put("https://boba.vn/micro-thu-am-nhac-cu", new String[]{"working", "hallway"});
        mapping.put("https://boba.vn/amply-mini-gia-re-tphcm", new String[]{"working", "living", "hallway"});
        mapping.put("https://boba.vn/amply-nghe-nhac", new String[]{"working", "living", "hallway"});
        mapping.put("https://boba.vn/phu-kien-am-thanh", new String[]{"working", "living", "hallway", "bed"});
        mapping.put("https://boba.vn/amply-hat-karaoke", new String[]{"working", "living", "hallway"});
        mapping.put("https://boba.vn/pin-sac-du-phong", new String[]{"working", "living", "kitchen", "hallway", "bed", "garage", "other"});
        mapping.put("https://boba.vn/gay-selfie", new String[]{"working", "living", "other"});
        mapping.put("https://boba.vn/gia-do-de-kep-dien-thoai", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/cap-sac-cap-du-lieu", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/bo-sac-pin-sac-da-nang", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/the-nho-chinh-hang-gia-re", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/lens-dien-thoai-gia-re", new String[]{"working"});
        mapping.put("https://boba.vn/tui-bao-ve-dien-thoai", new String[]{"other"});
        mapping.put("https://boba.vn/chan-do-dien-thoai-tripod-monopod", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/coc-cap-sac-nhanh-cho-dien-thoai", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/gay-chong-rung-gimbal", new String[]{"other"});
        mapping.put("https://boba.vn/camera-ip-wifi-thong-minh", new String[]{"working", "living", "kitchen", "hallway", "bed", "yard", "garage", "other"});
        mapping.put("https://boba.vn/camera-quan-sat", new String[]{"working", "living", "kitchen", "hallway", "bed", "yard", "garage", "other"});
        mapping.put("https://boba.vn/thiet-bi-bao-dong", new String[]{"working", "bed", "yard", "garage", "other"});
        mapping.put("https://boba.vn/o-cung-luu-tru-chuyen-cho-dau-ghi-nvr", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/bo-kit-camera-khong-day-dau-ghi-nvr", new String[]{"working", "living", "kitchen", "hallway", "bed", "yard", "garage", "other"});
        mapping.put("https://boba.vn/kinh-thuc-te-ao", new String[]{"working", "living", "hallway", "bed"});
        mapping.put("https://boba.vn/camera-mini-wifi", new String[]{"working", "living", "kitchen", "hallway", "bed", "yard", "garage", "other"});
        mapping.put("https://boba.vn/thiet-bi-dinh-vi-theo-doi-tu-xa", new String[]{"other"});
        mapping.put("https://boba.vn/sung-thuc-te-ao-argun", new String[]{"bed"});
        mapping.put("https://boba.vn/kinh-phong-to-man-hinh-dien-thoai", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/thiet-bi-kich-song-wifi", new String[]{"working", "living", "kitchen", "hallway", "bed"});
        mapping.put("https://boba.vn/thiet-bi-phat-song-wifi-3g-4g", new String[]{"working", "living", "kitchen", "hallway", "bed"});
        mapping.put("https://boba.vn/router-phat-song-wifi", new String[]{"working", "living", "kitchen", "hallway", "bed"});
        mapping.put("https://boba.vn/thiet-bi-ket-noi-mang", new String[]{"working", "living", "kitchen", "hallway", "bed"});
        mapping.put("https://boba.vn/usb-thu-wifi", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/sim-4g-data-toc-do-cao", new String[]{"working", "living", "kitchen", "hallway", "bed", "yard", "garage", "other"});
        mapping.put("https://boba.vn/usb-dcom-3g-4g", new String[]{"working", "living", "kitchen", "hallway", "bed", "yard", "garage", "other"});
        mapping.put("https://boba.vn/print-server", new String[]{"working"});
        mapping.put("https://boba.vn/de-tan-nhiet-laptop", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/cap-ket-noi-du-lieu", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/ban-phim-gia-co", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/chuot-game-thu", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/phu-kien-khac", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/ban-phim-bluetooth", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/ban-phim-co-tphcm", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/ban-phim-may-tinh", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/chuot-khong-day-wireless-bluetooth", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/webcam-chinh-hang-gia-re", new String[]{"working", "living", "kitchen", "hallway", "bed", "bath", "yard", "garage", "other"});
        mapping.put("https://boba.vn/tuong-trang-tri-goc-gaming-gear", new String[]{"working", "living", "kitchen", "bed", "bath"});
        mapping.put("https://boba.vn/ke-treo-loa-thung-da-nang", new String[]{"working", "living"});
        mapping.put("https://boba.vn/ke-treo-tivi-da-nang", new String[]{"working", "living", "kitchen", "bed"});
        mapping.put("https://boba.vn/gia-treo-tivi-gat-gu-nghieng-xeo", new String[]{"working", "living", "kitchen", "bed"});
        mapping.put("https://boba.vn/gia-treo-tivi-xoay-180-do", new String[]{"working", "living", "kitchen", "bed"});
        mapping.put("https://boba.vn/gia-treo-tivi-xoay-truc-ngang", new String[]{"working", "living", "kitchen", "bed"});
        mapping.put("https://boba.vn/gia-treo-man-pc-don-kep", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/gia-ke-treo-tivi-di-dong-co-banh", new String[]{"working", "living", "kitchen", "bed"});
        mapping.put("https://boba.vn/gia-treo-tivi-may-chieu-tha-tran", new String[]{"working", "living", "kitchen", "bed"});
        mapping.put("https://boba.vn/tay-cam-choi-game", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/may-choi-game-cam-tay", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/ban-choi-game-joystick-gia-re", new String[]{"bed"});
        mapping.put("https://boba.vn/phu-kien-va-dich-vu-sua-chua-tay-game", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/ban-phim-game-mot-tay-single-handedly", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/tay-cam-gamepad-mot-ben", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/but-trinh-chieu", new String[]{"working"});
        mapping.put("https://boba.vn/gia-treo-may-chieu", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/android-tivi-box", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/hdmi-khong-day", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/day-cap-tivi", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/remote-ban-phim-tivi", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/cong-chia-gop-chuyen-tin-hieu-tivi", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/phu-kien-tivi-khac", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/kinh-xem-tivi-kinh-3d-phan-cuc", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/cap-hdmi-4k-hdr", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/window-tivi-box", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/android-tv-stick", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/may-xay-sinh-to", new String[]{"kitchen"});
        mapping.put("https://boba.vn/may-moc-thiet-bi-dien-nha-bep", new String[]{"kitchen"});
        mapping.put("https://boba.vn/may-lam-toi-den-gia-re", new String[]{"kitchen"});
        mapping.put("https://boba.vn/binh-dun-sieu-toc-gia-re", new String[]{"working", "living", "kitchen"});
        mapping.put("https://boba.vn/may-lam-kem-da-nang", new String[]{"kitchen"});
        mapping.put("https://boba.vn/lo-nuong-bep-nuong-dien", new String[]{"yard"});
        mapping.put("https://boba.vn/may-lam-banh-da-nang", new String[]{"kitchen"});
        mapping.put("https://boba.vn/binh-giu-nhiet-ly-giu-nhiet", new String[]{"working", "living", "kitchen", "hallway", "bed"});
        mapping.put("https://boba.vn/may-pha-ca-phe-coc-tu-khuay-ca-phe", new String[]{"kitchen"});
        mapping.put("https://boba.vn/chao-dien-gia-re-chao-chong-dinh", new String[]{"kitchen"});
        mapping.put("https://boba.vn/may-danh-trung-cam-tay", new String[]{"kitchen"});
        mapping.put("https://boba.vn/can-hanh-ly-xach-tay", new String[]{"hallway", "bed", "garage"});
        mapping.put("https://boba.vn/can-tieu-ly-cam-tay", new String[]{"kitchen", "hallway", "yard", "garage", "other"});
        mapping.put("https://boba.vn/can-nha-bep-mini", new String[]{"kitchen"});
        mapping.put("https://boba.vn/can-suc-khoe-gia-re", new String[]{"hallway", "bed", "bath", "garage"});
        mapping.put("https://boba.vn/can-phan-tich-co-the", new String[]{"hallway", "bed", "bath", "garage"});
        mapping.put("https://boba.vn/den-ngu-den-led", new String[]{"working", "living", "kitchen", "hallway", "bed", "bath", "yard", "garage", "other"});
        mapping.put("https://boba.vn/den-led-den-trang-tri-ngoai-troi", new String[]{"yard"});
        mapping.put("https://boba.vn/den-cam-bien-thong-minh", new String[]{"working", "living", "kitchen", "hallway", "bed", "yard", "garage", "other"});
        mapping.put("https://boba.vn/den-bat-muoi", new String[]{"working", "living", "kitchen", "hallway", "bed", "garage", "other"});
        mapping.put("https://boba.vn/den-led-de-ban", new String[]{"working", "living", "kitchen", "hallway", "bed", "garage", "other"});
        mapping.put("https://boba.vn/thiet-bi-dien-gia-dung", new String[]{"working", "living", "kitchen", "hallway", "bed", "bath", "yard", "garage", "other"});
        mapping.put("https://boba.vn/ban-ui-mini-ban-ui-hoi-nuoc", new String[]{"hallway", "bed"});
        mapping.put("https://boba.vn/may-hut-bui-gia-re-hut-bui-cam-tay", new String[]{"working", "living", "kitchen", "hallway", "bed", "yard", "garage", "other"});
        mapping.put("https://boba.vn/thiet-bi-nha-thong-minh-smart-home", new String[]{"working", "living", "kitchen", "hallway", "bed", "garage", "other"});
        mapping.put("https://boba.vn/quat-hoi-nuoc-dieu-hoa-mini", new String[]{"working", "living", "kitchen", "hallway", "bed", "yard"});
        mapping.put("https://boba.vn/may-giat-gia-re-may-giat-mini-cam-tay", new String[]{"bath", "yard", "garage", "other"});
        mapping.put("https://boba.vn/may-loc-khong-khi-gia-re", new String[]{"working", "living", "kitchen", "hallway", "bed", "other"});
        mapping.put("https://boba.vn/robot-hut-bui-thong-minh", new String[]{"working", "living", "kitchen", "hallway", "bed", "garage", "other"});
        mapping.put("https://boba.vn/dong-ho-thong-minh", new String[]{"working", "living", "kitchen", "hallway", "bed", "yard", "garage", "other"});
        mapping.put("https://boba.vn/dong-ho-thoi-trang", new String[]{"working", "living", "kitchen", "hallway", "bed", "yard", "garage", "other"});
        mapping.put("https://boba.vn/dong-ho-tre-em", new String[]{"working", "living", "kitchen", "hallway", "bed", "yard", "garage", "other"});
        mapping.put("https://boba.vn/dong-ho-dinh-vi-tre-em", new String[]{"working", "living", "kitchen", "hallway", "bed", "yard", "garage", "other"});
        mapping.put("https://boba.vn/dong-ho-thoi-trang-nu", new String[]{"working", "living", "kitchen", "hallway", "bed", "yard", "garage", "other"});
        mapping.put("https://boba.vn/dong-ho-thoi-trang-doi", new String[]{"working", "living", "kitchen", "hallway", "bed", "yard", "garage", "other"});
        mapping.put("https://boba.vn/vong-deo-tay-suc-khoe", new String[]{"working", "living", "kitchen", "hallway", "bed", "yard", "garage", "other"});
        mapping.put("https://boba.vn/dong-ho-dinh-vi-gps-thoi-trang", new String[]{"working", "living", "kitchen", "hallway", "bed", "yard", "garage", "other"});
        mapping.put("https://boba.vn/dong-ho-dien-tu-dep", new String[]{"working", "living", "kitchen", "hallway", "bed", "bath", "garage", "other"});
        mapping.put("https://boba.vn/do-dung-sinh-hoat-trong-nha", new String[]{"other"});
        mapping.put("https://boba.vn/tu-ke-dung-do-da-nang-trong-nha", new String[]{"bed", "bath"});
        mapping.put("https://boba.vn/ke-dung-giay-da-nang", new String[]{"working", "living", "kitchen", "hallway", "bed", "bath", "yard", "garage", "other"});
        mapping.put("https://boba.vn/tui-vai-dung-do-da-nang", new String[]{"working", "living", "kitchen", "hallway", "bed"});
        mapping.put("https://boba.vn/quat-cam-tay-mini", new String[]{"working", "living", "kitchen", "hallway", "bed", "bath", "yard", "garage", "other"});
        mapping.put("https://boba.vn/quat-mini-de-ban", new String[]{"working", "living", "kitchen", "hallway", "bed", "bath", "yard", "garage", "other"});
        mapping.put("https://boba.vn/may-tao-do-am-khong-khi", new String[]{"working", "living", "kitchen", "hallway", "bed"});
        mapping.put("https://boba.vn/may-lanh-mini-de-ban", new String[]{"working", "living", "kitchen", "hallway", "bed"});
        mapping.put("https://boba.vn/o-khoa-thong-minh", new String[]{"working", "living", "hallway", "bed", "yard", "garage", "other"});
        mapping.put("https://boba.vn/khoa-bao-dong-chong-trom", new String[]{"hallway", "yard", "garage", "other"});
        mapping.put("https://boba.vn/o-khoa-chong-cat", new String[]{"hallway", "yard", "garage", "other"});
        mapping.put("https://boba.vn/moc-khoa-thoi-trang", new String[]{"other"});
        mapping.put("https://boba.vn/dong-ho-treo-tuong-dep", new String[]{"working", "living", "kitchen", "hallway", "bed"});
        mapping.put("https://boba.vn/den-chieu-sang", new String[]{"working", "living", "kitchen", "hallway", "bed", "bath", "garage"});
        mapping.put("https://boba.vn/decal-trang-tri-dan-tuong", new String[]{"living", "hallway", "bed"});
        mapping.put("https://boba.vn/thac-khoi-tram-huong", new String[]{"hallway", "other"});
        mapping.put("https://boba.vn/tuong-da-va-go-phong-thuy", new String[]{"working", "living", "hallway", "bed", "bath", "other"});
        mapping.put("https://boba.vn/dung-cu-nha-bep-gia-re", new String[]{"kitchen"});
        mapping.put("https://boba.vn/dung-cu-lam-banh-lam-kem", new String[]{"kitchen"});
        mapping.put("https://boba.vn/hop-dung-thuc-pham-gia-vi", new String[]{"kitchen"});
        mapping.put("https://boba.vn/may-khoan-va-dung-cu-da-nang", new String[]{"garage"});
        mapping.put("https://boba.vn/bo-tua-vit-sua-chua-da-nang", new String[]{"garage"});
        mapping.put("https://boba.vn/may-cua-mini-cam-tay", new String[]{"yard", "garage"});
        mapping.put("https://boba.vn/sung-ban-keo", new String[]{"working", "garage", "other"});
        mapping.put("https://boba.vn/kim-da-nang-kim-bam-chet", new String[]{"garage"});
        mapping.put("https://boba.vn/dau-han-xi-mo-han-chi", new String[]{"other"});
        mapping.put("https://boba.vn/thuoc-keo-xay-dung", new String[]{"other"});
        mapping.put("https://boba.vn/bang-keo-dan-thung-bang-keo-dien", new String[]{"working", "living", "kitchen", "hallway", "bed", "garage", "other"});
        mapping.put("https://boba.vn/thuoc-do-laser", new String[]{"garage"});
        mapping.put("https://boba.vn/voi-sen-tang-ap-nha-tam", new String[]{"bath"});
        mapping.put("https://boba.vn/dung-cu-lau-chui-nha-cua", new String[]{"garage"});
        mapping.put("https://boba.vn/voi-rua-xe-tang-ap", new String[]{"yard", "garage"});
        mapping.put("https://boba.vn/voi-rua-chen-bat-nha-bep", new String[]{"kitchen"});
        mapping.put("https://boba.vn/phu-kien-trau-cay-bitcoin", new String[]{"working"});
        mapping.put("https://boba.vn/may-quet-ma-vach-khong-day", new String[]{"working", "other"});
        mapping.put("https://boba.vn/may-in", new String[]{"working"});
        mapping.put("https://boba.vn/may-do-huyet-ap", new String[]{"bed", "other"});
        mapping.put("https://boba.vn/dai-nep-y-te", new String[]{"other"});
        mapping.put("https://boba.vn/thiet-bi-y-te-khac", new String[]{"bed", "other"});
        mapping.put("https://boba.vn/may-noi-soi-chuyen-khoa", new String[]{"bed", "other"});
        mapping.put("https://boba.vn/may-do-huyet-ap-bap-tay", new String[]{"bed", "other"});
        mapping.put("https://boba.vn/may-massage-cam-tay", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/goi-massage", new String[]{"working", "bed"});
        mapping.put("https://boba.vn/giuong-dem-massage", new String[]{"living", "bed"});
        mapping.put("https://boba.vn/dung-cu-massage-mat", new String[]{"bed", "bath"});
        mapping.put("https://boba.vn/dung-cu-massage-vat-ly-tri-lieu", new String[]{"working", "hallway", "bed"});
        mapping.put("https://boba.vn/dung-cu-massage-chan", new String[]{"hallway", "bed"});
        mapping.put("https://boba.vn/dai-massage-mong-bung", new String[]{"hallway", "bed"});
        mapping.put("https://boba.vn/may-massage-chan", new String[]{"bath"});
        mapping.put("https://boba.vn/thiet-bi-cham-soc-khac", new String[]{"other"});
        mapping.put("https://boba.vn/may-hut-mun", new String[]{"bath"});
        mapping.put("https://boba.vn/may-cham-soc-mong", new String[]{"bed", "bath"});
        mapping.put("https://boba.vn/may-tia-tay-long", new String[]{"bath"});
        mapping.put("https://boba.vn/dung-cu-cham-soc-rang-mieng", new String[]{"bath"});
        mapping.put("https://boba.vn/may-cha-got-chan", new String[]{"bed", "bath"});
        mapping.put("https://boba.vn/thiet-bi-lam-dep", new String[]{"bed", "bath"});
        mapping.put("https://boba.vn/guong-trang-diem", new String[]{"bed", "bath"});
        mapping.put("https://boba.vn/thiet-bi-nha-khoa", new String[]{"bath"});
        mapping.put("https://boba.vn/may-xong-tinh-dau", new String[]{"working", "living", "hallway", "bed", "bath"});
        mapping.put("https://boba.vn/tong-do-keo-cat-toc", new String[]{"bath"});
        mapping.put("https://boba.vn/may-tao-kieu-toc", new String[]{"bed", "bath"});
        mapping.put("https://boba.vn/may-cao-rau", new String[]{"bath"});
        mapping.put("https://boba.vn/may-say-toc", new String[]{"bed", "bath"});
        mapping.put("https://boba.vn/keo-cat-toc-chuyen-nghiep", new String[]{"bed", "bath"});
        mapping.put("https://boba.vn/dung-cu-may-tap-bung", new String[]{"hallway", "other"});
        mapping.put("https://boba.vn/dung-cu-tap-the-duc-khac", new String[]{"hallway", "other"});
        mapping.put("https://boba.vn/xa-don", new String[]{"hallway", "other"});
        mapping.put("https://boba.vn/gang-tay-lai-xe", new String[]{"garage", "other"});
        mapping.put("https://boba.vn/den-xe-dap", new String[]{"garage", "other"});
        mapping.put("https://boba.vn/khoa-xe-dap", new String[]{"garage", "other"});
        mapping.put("https://boba.vn/phu-kien-xe-dap-khac", new String[]{"garage", "other"});
        mapping.put("https://boba.vn/kinh-di-boi", new String[]{"bed", "other"});
        mapping.put("https://boba.vn/dung-cu-da-nang", new String[]{"other"});
        mapping.put("https://boba.vn/den-bao-nang-luong-mat-troi", new String[]{"yard", "garage", "other"});
        mapping.put("https://boba.vn/den-pin-doi", new String[]{"yard", "garage", "other"});
        mapping.put("https://boba.vn/den-pin-da-nang", new String[]{"working", "living", "kitchen", "hallway", "bed", "bath", "yard", "garage", "other"});
        mapping.put("https://boba.vn/leu-trai-du-lich-xep-gon", new String[]{"other"});
        mapping.put("https://boba.vn/tui-ngu-du-lich-trum-kin-nguoi", new String[]{"other"});
        mapping.put("https://boba.vn/ong-nhom-du-lich-gia-re", new String[]{"other"});
        mapping.put("https://boba.vn/ong-nham-laze-do-khoang-cach", new String[]{"other"});
        mapping.put("https://boba.vn/robot-thu-cung", new String[]{"other"});
        mapping.put("https://boba.vn/den-chieu-sang1", new String[]{"working", "living", "kitchen", "hallway", "bed", "bath", "yard", "garage", "other"});
        mapping.put("https://boba.vn/thiet-bi-thong-minh-google", new String[]{"working", "living", "bed"});
        mapping.put("https://boba.vn/cong-tac-thong-minh", new String[]{"working", "living", "kitchen", "hallway", "bed", "bath", "yard", "garage", "other"});
        mapping.put("https://boba.vn/may-bom-tang-ap-mini", new String[]{"yard"});
        mapping.put("https://boba.vn/may-bom-bien-tang", new String[]{"yard"});
        mapping.put("https://boba.vn/may-bom-phun-suong", new String[]{"yard"});
        mapping.put("https://boba.vn/may-bom-tang-ap-chim-12v", new String[]{"yard"});
        mapping.put("https://boba.vn/may-bom-nuoc-ho-ca", new String[]{"yard"});
        mapping.put("https://boba.vn/he-thong-may-phun-suong-mini", new String[]{"yard"});
        mapping.put("https://boba.vn/phu-kien-he-thong-phun-suong", new String[]{"yard"});
        mapping.put("https://boba.vn/he-thong-tuoi-lan-va-tuoi-cay-tu-dong", new String[]{"yard"});
        MAPPING_USAGE = Collections.unmodifiableMap(mapping);
    }

}
